{
 "title": "CompassVPN Dashboard",
 "description": "The CompassVPN Dashboard provides comprehensive real-time monitoring of VPN infrastructure, featuring server performance metrics, Xray traffic analytics, and VPN configuration management. Track system resources, user connections, bandwidth usage, and security metrics in a unified interface.",
 "tags": [ "compassvpn" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   },
   {
    "name": "donor",
    "label": "Donor",
    "query": {
     "query": "label_values(node_cpu_seconds_total,donor)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(v2ray_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Real-Time Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "v2ray_uptime_seconds{donor=\"$donor\", instance=~\"$instance\"}"
    },
    {
     "expr": "sum by (instance) (increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"inbound\"}[$__range]))"
    },
    {
     "expr": "{\"$v2ray_traffic_uplink_bytes_total\", job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{donor=\"$donor\", instance=~\"$instance\"}[30m]))",
     "legendFormat": "Downlink"
    },
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\"}[30m]))",
     "legendFormat": "Uplink"
    },
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{donor=\"$donor\", instance=~\"$instance\"}[30m])) \r\n+\r\nsum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\", instance=~\"$instance\"}[30m]))",
     "legendFormat": "Total Bandwidth"
    }
   ]
  },
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{donor=\"$donor\", mode=\"system\",instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "IOwait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "IRQ"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{donor=\"$donor\", instance=~\"$node\"} - node_memory_MemFree_bytes{donor=\"$donor\", instance=~\"$node\"} - (node_memory_Cached_bytes{donor=\"$donor\", instance=~\"$node\"} + node_memory_Buffers_bytes{donor=\"$donor\", instance=~\"$node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{donor=\"$donor\", instance=~\"$node\"}[30m]) + irate(node_network_receive_bytes_total{donor=\"$donor\", instance=~\"$node\"}[30m])",
     "legendFormat": "{{device}} - Total"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{donor=\"$donor\", instance=~\"$node\"}[30m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{donor=\"$donor\", instance=~\"$node\"}[30m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\",device!~'rootfs', mountpoint='/'}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_size_bytes{donor=\"$donor\", instance=~\"$node\",device!~'rootfs', mountpoint='/'} - node_filesystem_avail_bytes{donor=\"$donor\", instance=~\"$node\",device!~'rootfs', mountpoint='/'}",
     "legendFormat": "root - /"
    }
   ]
  },
  {
   "title": "Total Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "(\r\n  node_network_transmit_bytes_total{instance=\"$node\", device=\"eth0\"} or \r\n  node_network_transmit_bytes_total{instance=\"$node\", device=\"venet0\"} or \r\n  node_network_transmit_bytes_total{instance=\"$node\", device=\"ens3\"}\r\n) +\r\n(\r\n  node_network_receive_bytes_total{instance=\"$node\", device=\"eth0\"} or \r\n  node_network_transmit_bytes_total{instance=\"$node\", device=\"venet0\"} or \r\n  node_network_transmit_bytes_total{instance=\"$node\", device=\"ens3\"}\r\n)\r\n",
     "legendFormat": "Total"
    },
    {
     "expr": "node_network_receive_bytes_total{instance=\"$node\", device=\"eth0\"} or node_network_transmit_bytes_total{instance=\"$node\", device=\"venet0\"} or node_network_transmit_bytes_total{instance=\"$node\", device=\"ens3\"}",
     "legendFormat": "{{device}} - Transmit"
    },
    {
     "expr": "node_network_transmit_bytes_total{donor=\"$donor\", instance=\"$node\", device=\"eth0\"} or node_network_transmit_bytes_total{donor=\"$donor\", instance=\"$node\", device=\"venet0\"} or node_network_transmit_bytes_total{donor=\"$donor\", instance=\"$node\", device=\"ens3\"}",
     "legendFormat": "{{device}} - Receive"
    }
   ]
  },
  { "title": "XRAY Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Upload Speed of Inbounds",
   "type": "timeseries",
   "description": "Upload Speed of each Inbound",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{donor=\"$donor\", instance=~\"$instance\", dimension=\"inbound\", target!=\"doko\"}[30m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Inbounds",
   "type": "timeseries",
   "description": "Download Speed of each Inbound",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{donor=\"$donor\", instance=~\"$instance\", dimension=\"inbound\", target!=\"doko\"}[30m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Active Unique Users",
   "type": "timeseries",
   "description": "Number of unique users actively connected to the server. (Approximately)",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "xray_unique_users{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{donor}}"
    }
   ]
  },
  {
   "title": "Current Unique Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_unique_users{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{donor}}"
    }
   ]
  },
  {
   "title": "Total Connection Count",
   "type": "timeseries",
   "description": "Total number of connections established over time. This includes all connection attempts, including reconnections.",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "xray_total_connections{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{donor}}"
    }
   ]
  },
  {
   "title": "Current Total Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_total_connections{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{donor}}"
    }
   ]
  },
  {
   "title": "Connections per User",
   "type": "timeseries",
   "description": "Average number of connections per unique user.",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "xray_total_connections{donor=~\"$donor\", instance=~\"$instance\"} / xray_unique_users{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{donor}}"
    }
   ]
  },
  {
   "title": "Current Connections per User",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_total_connections{donor=~\"$donor\", instance=~\"$instance\"} / xray_unique_users{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{donor}}"
    }
   ]
  },
  { "title": "XRAY Routing Rules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Blocked Requests",
   "type": "timeseries",
   "description": "Number of requests blocked by routing rules over time period.",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "xray_blocked_requests{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{donor}}"
    }
   ]
  },
  {
   "title": "Blocked Requests Percentage",
   "type": "stat",
   "description": "Percentage of requests that are blocked by routing rules.",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_blocked_percentage{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_total_connections{donor=~\"$donor\", instance=~\"$instance\"} - xray_blocked_requests{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "Allowed"
    },
    {
     "expr": "xray_blocked_requests{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "Blocked"
    }
   ]
  },
  { "title": "VPN Configurations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "VPN Configuration Links",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "vpn_config{donor=\"$donor\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}