{
 "title": "CompassVPN Dashboard",
 "description": "The CompassVPN Dashboard provides comprehensive real-time monitoring of VPN infrastructure, featuring server performance metrics, Xray traffic analytics, and VPN configuration management. Track system resources, user connections, bandwidth usage, and security metrics in a unified interface.",
 "tags": [ "compassvpn" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "donor", "label": "Donor", "query": { "query": "label_values(donor)" } },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(topk(100, increase(node_network_receive_bytes_total[1d])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Up / Down Instances",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count((v2ray_up == 1) and ignoring(v2ray_up) v2ray_up)",
       "legendFormat": "Up"
      },
      {
       "expr": "(count(v2ray_up) != 1) and ignoring(v2ray_up) v2ray_up",
       "legendFormat": "Down"
      }
     ]
    },
    {
     "title": "Overview",
     "type": "table",
     "gridPos": { "h": 12, "w": 21, "x": 3, "y": 1 },
     "targets": [
      {
       "expr": "v2ray_uptime_seconds{donor=~\"$donor\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (instance) (increase(node_network_receive_bytes_total{donor=~\"$donor\", instance=~\"$instance\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (instance) (increase(node_network_transmit_bytes_total{donor=~\"$donor\", instance=~\"$instance\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{donor=~\"$donor\", instance=~\"$instance\"}[1h])) by (instance)",
       "legendFormat": "{{instance}} - Downlink"
      },
      {
       "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{donor=~\"$donor\",instance=~\"$instance\"}[1h])) by (instance)",
       "legendFormat": "{{instance}} - Uplink"
      }
     ]
    }
   ]
  },
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{donor=~\"$donor\", instance=~\"$instance\", mode=\"system\"}[1h])) * 100",
     "legendFormat": "{{instance}} - System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{donor=~\"$donor\", instance=~\"$instance\", mode='user'}[1h])) * 100",
     "legendFormat": "{{instance}} - User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{donor=~\"$donor\", mode='iowait',instance=~\"$instance\"}[1h])) * 100",
     "legendFormat": "{{instance}} - IOwait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{donor=~\"$donor\", mode=~\".*irq\",instance=~\"$instance\"}[1h])) * 100",
     "legendFormat": "{{instance}} - IRQ"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{donor=~\"$donor\", instance=~\"$instance\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[1h])) * 100",
     "legendFormat": "{{instance}} - Used"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{donor=~\"$donor\", mode='idle', instance=~\"$instance\"}[1h])) * 100",
     "legendFormat": "{{instance}} - Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{donor=~\"$donor\", instance=~\"$instance\"} - node_memory_MemFree_bytes{donor=~\"$donor\", instance=~\"$instance\"} - (node_memory_Cached_bytes{donor=~\"$donor\", instance=~\"$instance\"} + node_memory_Buffers_bytes{donor=~\"$donor\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{donor=~\"$donor\", instance=~\"$instance\"} + node_memory_Buffers_bytes{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - RAM C+B"
    },
    {
     "expr": "node_memory_MemFree_bytes{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - RAM Free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{donor=~\"$donor\", instance=~\"$instance\"}[1h]) + irate(node_network_transmit_bytes_total{donor=~\"$donor\", instance=~\"$instance\"}[1h])",
     "legendFormat": "{{instance}} - {{device}} - Total"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{donor=~\"$donor\", instance=~\"$instance\"}[1h])",
     "legendFormat": "{{instance}} - {{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{donor=~\"$donor\", instance=~\"$instance\"}[1h])",
     "legendFormat": "{{instance}} - {{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{donor=~\"$donor\", instance=~\"$instance\",device!~'rootfs', mountpoint='/'} - node_filesystem_avail_bytes{donor=~\"$donor\", instance=~\"$instance\",device!~'rootfs', mountpoint='/'}",
     "legendFormat": "{{instance}} - Used"
    },
    {
     "expr": "node_filesystem_size_bytes{donor=~\"$donor\", instance=~\"$instance\", device!~'rootfs', mountpoint='/'}",
     "legendFormat": "{{instance}} - Total"
    }
   ]
  },
  {
   "title": "Total Network Usage",
   "type": "stat",
   "description": "Total Network Usage for each device and donor",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (\r\n  increase(node_network_receive_bytes_total{donor=~\"$donor\", instance=~\"$instance\"}[$__range]) +\r\n  increase(node_network_transmit_bytes_total{donor=~\"$donor\", instance=~\"$instance\"}[$__range])\r\n)\r\n",
     "legendFormat": "{{instance}} - Total"
    },
    {
     "expr": "increase(node_network_receive_bytes_total{donor=~\"$donor\", instance=~\"$instance\"}[$__range]) > 100000000",
     "legendFormat": "{{instance}} - {{device}} - Transmit"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{donor=~\"$donor\", instance=~\"$instance\"}[$__range]) > 100000000",
     "legendFormat": "{{instance}} - {{device}} - Receive"
    }
   ]
  },
  { "title": "XRAY Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Upload Speed of Inbounds",
   "type": "timeseries",
   "description": "Upload Speed of each Inbound",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{donor=~\"$donor\", instance=~\"$instance\", dimension=~\"inbound\", target!=\"doko\"}[1h])",
     "legendFormat": "{{instance}} - {{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Inbounds",
   "type": "timeseries",
   "description": "Download Speed of each Inbound",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{donor=~\"$donor\", instance=~\"$instance\", dimension=~\"inbound\", target!=\"doko\"}[1h])",
     "legendFormat": "{{instance}} - {{target}}"
    }
   ]
  },
  {
   "title": "Active Unique Users",
   "type": "timeseries",
   "description": "Number of unique users actively connected to the server. (Approximately)",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "xray_unique_users{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{donor}}"
    }
   ]
  },
  {
   "title": "Current Unique Users",
   "type": "stat",
   "description": "Approximation of current unique users for the last 2 minutes.",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_unique_users{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Connection Count",
   "type": "timeseries",
   "description": "Total number of connections established over time. This includes all connection attempts, including reconnections.",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "xray_total_connections{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{donor}}"
    }
   ]
  },
  {
   "title": "Current Total Connections",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_total_connections{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections per User",
   "type": "timeseries",
   "description": "Average number of connections per unique user.",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "xray_total_connections{donor=~\"$donor\", instance=~\"$instance\"} / xray_unique_users{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{donor}}"
    }
   ]
  },
  {
   "title": "Current Connections per User",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_total_connections{donor=~\"$donor\", instance=~\"$instance\"} / xray_unique_users{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "XRAY Routing Rules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Blocked Requests",
   "type": "timeseries",
   "description": "Number of requests blocked by routing rules over time period.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "xray_blocked_requests{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{donor}}"
    }
   ]
  },
  {
   "title": "Blocked Requests Percentage",
   "type": "stat",
   "description": "Percentage of requests that are blocked by routing rules.",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_blocked_percentage{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xray_total_connections{donor=~\"$donor\", instance=~\"$instance\"} - xray_blocked_requests{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Allowed"
    },
    {
     "expr": "xray_blocked_requests{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Blocked"
    }
   ]
  },
  { "title": "VPN Configurations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "VPN Configuration Links",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "vpn_config{donor=~\"$donor\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}