{
 "title": "Servers Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   },
   {
    "name": "donor",
    "label": "Donor",
    "query": {
     "query": "label_values(node_cpu_seconds_total,donor)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{donor=\"$donor\", instance=\"$node\", device=\"eth0\"} or node_network_transmit_bytes_total{donor=\"$donor\", instance=\"$node\", device=\"venet0\"} or node_network_transmit_bytes_total{donor=\"$donor\", instance=\"$node\", device=\"ens3\"}",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "node_network_receive_bytes_total{instance=\"$node\", device=\"eth0\"} or node_network_transmit_bytes_total{instance=\"$node\", device=\"venet0\"} or node_network_transmit_bytes_total{instance=\"$node\", device=\"ens3\"}",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{donor=\"$donor\", mode=\"system\",instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "IOwait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "IRQ"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$node\"}[30m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{donor=\"$donor\", instance=~\"$node\", device=\"eth0\"}[30m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node\", device=\"eth0\"}[30m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "legendFormat": "RAM Total" },
    {
     "expr": "node_memory_MemTotal_bytes{donor=\"$donor\", instance=~\"$node\"} - node_memory_MemFree_bytes{donor=\"$donor\", instance=~\"$node\"} - (node_memory_Cached_bytes{donor=\"$donor\", instance=~\"$node\"} + node_memory_Buffers_bytes{donor=\"$donor\", instance=~\"$node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Free space - /",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{donor=\"$donor\", instance=~\"$node\",device!~'rootfs', mountpoint='/'} - node_filesystem_avail_bytes{donor=\"$donor\", instance=~\"$node\",device!~'rootfs', mountpoint='/'}",
     "legendFormat": "root - /"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\",device!~'rootfs', mountpoint='/'}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}