{
 "title": "XRay Traffic Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(v2ray_up,instance)"
    }
   },
   { "name": "donor", "label": "Donor", "query": { "query": "label_values(v2ray_up,donor)" } }
  ]
 },
 "panels": [
  {
   "title": "V2Ray Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(v2ray_up{donor=~\"$donor\",instance=~\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "Real-Time Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "v2ray_uptime_seconds{donor=\"$donor\", instance=~\"$instance\"}"
    },
    {
     "expr": "sum by (instance) (increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"inbound\"}[$__range]))"
    },
    {
     "expr": "sum by (instance) (increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"inbound\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{donor=\"$donor\", instance=~\"$instance\",dimension=\"inbound\"}[30m]))",
     "legendFormat": "Downlink"
    },
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"inbound\"}[30m]))",
     "legendFormat": "Uplink"
    }
   ]
  },
  {
   "title": "V2Ray Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(v2ray_up{donor=~\"$donor\",instance=~\"$instance\"}) - count(v2ray_up{donor=~\"$donor\",instance=~\"$instance\"} == 1)"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "instance" },
  {
   "title": "Real-Time Detail Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(v2ray_traffic_downlink_bytes_total{donor=\"$donor\", instance=~\"$instance\",dimension=\"user\"}[$__range])"
    },
    {
     "expr": "increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"user\"}[$__range])"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{donor=\"$donor\", instance=~\"$instance\",dimension=\"inbound\"}[30m]))",
     "legendFormat": "Downlink"
    },
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"inbound\"}[30m]))",
     "legendFormat": "Uplink"
    }
   ]
  },
  {
   "title": "Download Speed of Inbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{donor=\"$donor\", instance=~\"$instance\",dimension=\"inbound\"}[30m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{donor=\"$donor\", instance=~\"$instance\",dimension=\"user\"}[30m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Inbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{donor=\"$donor\",instance=~\"$instance\",dimension=\"inbound\"}[30m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{donor=\"$donor\", instance=~\"$instance\",dimension=\"user\"}[30m])",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}